# Generated by Django 2.0.3 on 2018-06-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0002_auto_20180519_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='number_of_train_images',
            field=models.IntegerField(default=0),
        ),
    ]
