# Generated by Django 2.1.2 on 2018-10-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0003_member_number_of_train_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='unlock_server_room',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='is_go_in',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='result_auth',
            field=models.BooleanField(null=True),
        ),
    ]
